Logging started at 20:08:21 on 19 Jul 2017
QIIME version: 1.9.1

qiime_config values:
pick_otus_reference_seqs_fp	/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
sc_queue	all.q
pynast_template_alignment_fp	/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set_aligned/85_otus.pynast.fasta
cluster_jobs_fp	start_parallel_jobs.py
assign_taxonomy_reference_seqs_fp	/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/rep_set/97_otus.fasta
torque_queue	friendlyq
jobs_to_start	1
denoiser_min_per_core	50
assign_taxonomy_id_to_taxonomy_fp	/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime_default_reference/gg_13_8_otus/taxonomy/97_otu_taxonomy.txt
temp_dir	/var/folders/rd/6ytyj48n7nn4l2c6dfsdrccc0000gn/T/
blastall_fp	blastall
seconds_to_sleep	1

parameter file values:
parallel:jobs_to_start	1

Input file md5 sums:
./filtered_otu_table_94.biom: a225d0b6fabaf84fffad76556b5bb9d9
./AGP_metadata_subset_94.txt: cd70e6a490e307d361dc819c464d1c41
./ag_tree.tree: 4d03d2e6ebd837042fc60f5423f93e3e

Executing commands.

# Alpha rarefaction command 
multiple_rarefactions.py -i ./filtered_otu_table_94.biom -m 10 -x 1500 -s 149 -o arare_max1500//rarefaction/ 

Stdout:

Stderr:

# Alpha diversity on rarefied OTU tables command 
alpha_diversity.py -i arare_max1500//rarefaction/ -o arare_max1500//alpha_div/  -t ./ag_tree.tree



*** ERROR RAISED DURING STEP: Alpha diversity on rarefied OTU tables
Command run was:
 alpha_diversity.py -i arare_max1500//rarefaction/ -o arare_max1500//alpha_div/  -t ./ag_tree.tree
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/Users/maxabramson/miniconda3/envs/qiime1/bin/alpha_diversity.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'alpha_diversity.py')
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
    
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
    
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/alpha_diversity.py", line 131, in <module>
    main()
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/alpha_diversity.py", line 115, in main
    opts.tree_path)
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/alpha_diversity.py", line 379, in multiple_file_alpha
    output_fp, tree_path)
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/alpha_diversity.py", line 326, in single_file_alpha
    result_path=outfilepath, log_path=None)
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/util.py", line 259, in __call__
    result = self.getResult(*args, **kwargs)
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/alpha_diversity.py", line 199, in getResult
    sample_names=otu_table.ids())
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/util.py", line 259, in __call__
    result = self.getResult(*args, **kwargs)
  File "/Users/maxabramson/miniconda3/envs/qiime1/lib/python2.7/site-packages/qiime/alpha_diversity.py", line 116, in getResult
    data = otu_table.iter_data(axis='sample')
AttributeError: 'NoneType' object has no attribute 'iter_data'


Logging stopped at 20:16:58 on 19 Jul 2017
